Add navigation
proga-react-practice/sigma-team-project pull request #3
Opened 2024-05-04 05:33 UTC by OstapivIvan

Added navigation with logo, links and adaptive styles

2024-05-07 12:24 UTC, OstapivIvan commented
https://github.com/proga-react-practice/sigma-team-project/assets/123650171/647a43d7-e034-4cea-981e-23f2e8e1b110


https://github.com/proga-react-practice/sigma-team-project/assets/123650171/b46a538e-6b73-48ac-8cfa-b6e2c538465d

Navigation

2024-05-08 15:47 UTC, OliaZakharcuk reviewed
Can you center this? 
![image](https://github.com/proga-react-practice/sigma-team-project/assets/74414048/c1304432-7d54-4fe5-97f1-a3066247bdda)

2024-05-08 15:47 UTC, OliaZakharcuk commented
Add some space and make them the same size
![image](https://github.com/proga-react-practice/sigma-team-project/assets/74414048/6fca7a04-f76c-4eb6-a608-4e2f650777eb)

2024-05-08 15:49 UTC, OliaZakharcuk commented
replace with team contacts or drop as you already have logo on the other side
![image](https://github.com/proga-react-practice/sigma-team-project/assets/74414048/b0957059-d7e5-408a-854f-d51ad6154d68)

2024-05-08 15:56 UTC, OliaZakharcuk requested changes

2024-05-08 15:56 UTC, OliaZakharcuk commented on src/components/Header.tsx
> +        <ThemeProvider theme={theme}>
move to the highest level

2024-05-08 15:56 UTC, OliaZakharcuk commented on src/components/Header.tsx
> +                        "@media screen and (max-width: 426px)": {
try to use mui breakpoints

2024-05-08 15:56 UTC, OliaZakharcuk commented on src/components/Header.tsx
> +                                sx={{mt: "45px"}}
no hardcode

2024-05-08 15:56 UTC, OliaZakharcuk commented on src/components/Header.tsx
> +                                        content: '""',
Why is it needed?

2024-05-09 09:52 UTC, OliaZakharcuk approved these changes

2024-05-09 09:52 UTC, OliaZakharcuk commented on src/pages/Home.tsx
> +            <Container sx={{padding: 0}}>
Why do you need two containers?

2024-05-09 10:19 UTC, merged